name: Monorepo CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies (uv lock and sync)
        run: uv sync

      - name: Run Ruff (Linting)
        run: uv run ruff check .

      - name: Run Black (Formatting Check)
        run: uv run black --check .

      - name: Run sqlfluff
        run: uv run sqlfluff lint --project-dir .

      - name: dbt Debug (Check Snowflake Connectivity)
        env:
          SNOWFLAKE_ACCOUNT: xhvkqqr-kf74215
          SNOWFLAKE_USER: PANSTRAWBERRY
          SNOWFLAKE_PASSWORD: TuKaqndCQpJ7Jz4
          SNOWFLAKE_ROLE: SYSADMIN
          SNOWFLAKE_WAREHOUSE: compute_wh
          SNOWFLAKE_DATABASE: TEST_DB
          SNOWFLAKE_SCHEMA: PUBLIC
        run: |
          uv run dbt debug --project-dir dbt_project
